---
name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest"]
        ruby: ["3.4"]
    steps:
      - uses: actions/checkout@v3

      - uses: jbourassa/oxidize-rb-actions/setup-ruby-and-rust@main
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: latest
          bundler-cache: true
          cargo-cache: true
          cache-version: v2

      - name: Run ruby tests
        run: bundle exec rake compile && bundle exec ruby -rminitest/autorun -Itest test/oxi/test_test.rb

      - name: Lint rust
        run: cargo clippy && cargo fmt --check

      - name: Test source gem
        shell: bash
        run: |
          bundle exec rake build
          gem install --verbose pkg/*.gem

          if ruby -roxi/test -e "puts Oxi::Test.hello('world!')" | grep "Hello, world!"; then
            echo "Success"
          else
            echo "Failure"
            exit 1
          fi
